### ISSUE TITLE
This repo is a mess

### ISSUE THREAD

**Issue by mateoconlechuga** [KingDubDub/VYSION-Backgrounds#1]
It should have a makefile that I can use to quickly build all of the images via convimg. Only images should be in this repo, don't upload the appvars themselves as those should be part of a release. Also please avoid giving names like `"old file"` as git is perfectly capable of tracking things -- just delete the file itself.

**Comment by KingDubDub** [comment]
1. That makefile exists, just open powershell and run convimg, I don't deny it's a mess
2. The images and appvars are left due to multiple versions of convimg existing, most of this was made with compatibility in mind.
3. "old file" pre-dates the repo and was used by me for testing and, again, compatibility; it isn't included in the tracking. The repo was a spur-of-the-moment upload for someone who couldn't download files via discord.

Thanks for the tips and reminder to fix this!
